# Machine Learning Workflow
Complete the steps below to complete the machine learning workflow for this classifier.

# Instructor Solution

In [11]:
import nltk
nltk.download(['punkt', 'wordnet'])

import re
import numpy as np
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'


def load_data():
    df = pd.read_csv('corporate_messaging.csv', encoding='latin-1')
    df = df[(df["category:confidence"] == 1) & (df['category'] != 'Exclude')]
    X = df.text.values
    y = df.category.values
    return X, y


def tokenize(text):
    detected_urls = re.findall(url_regex, text)
    for url in detected_urls:
        text = text.replace(url, "urlplaceholder")

    tokens = word_tokenize(text)
    lemmatizer = WordNetLemmatizer()

    clean_tokens = []
    for tok in tokens:
        clean_tok = lemmatizer.lemmatize(tok).lower().strip()
        clean_tokens.append(clean_tok)

    return clean_tokens


def display_results(y_test, y_pred):
    labels = np.unique(y_pred)
    confusion_mat = confusion_matrix(y_test, y_pred, labels=labels)
    accuracy = (y_pred == y_test).mean()

    print("Labels:", labels)
    print("Confusion Matrix:\n", confusion_mat)
    print("Accuracy:", accuracy)


def main():
    X, y = load_data()
    X_train, X_test, y_train, y_test = train_test_split(X, y)

    vect = CountVectorizer(tokenizer=tokenize)
    tfidf = TfidfTransformer()
    clf = RandomForestClassifier()

    # train classifier
    X_train_counts = vect.fit_transform(X_train)
    print('X_train_counts shape:', X_train_counts.shape)
    X_train_tfidf = tfidf.fit_transform(X_train_counts)
    print('X_train_tfidf shape:', X_train_tfidf.shape)
    clf.fit(X_train_tfidf, y_train)

    # predict on test data
    X_test_counts = vect.transform(X_test)
    print('X_test_counts shape:', X_test_counts.shape)
    X_test_tfidf = tfidf.transform(X_test_counts)
    print('X_test_tfidf shape:', X_test_tfidf.shape)
    y_pred = clf.predict(X_test_tfidf)

    # display results
    display_results(y_test, y_pred)


main()

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/starplatinum87/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/starplatinum87/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


X_train_counts shape: (1802, 5532)
X_train_tfidf shape: (1802, 5532)
X_test_counts shape: (601, 5532)
X_test_tfidf shape: (601, 5532)
Labels: ['Action' 'Dialogue' 'Information']
Confusion Matrix:
 [[ 84   0  36]
 [  0  21   5]
 [  3   1 451]]
Accuracy: 0.9251247920133111


# Worked Solution

In [12]:
import nltk
nltk.download(['punkt', 'wordnet'])

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/starplatinum87/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/starplatinum87/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [13]:
import re
import pandas as pd
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [14]:
url_regex = 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'

def load_data():
    df = pd.read_csv('corporate_messaging.csv', encoding='latin-1')
    df = df[(df["category:confidence"] == 1) & (df['category'] != 'Exclude')]
    X = df.text.values
    y = df.category.values
    return X, y

def tokenize(text):
    detected_urls = re.findall(url_regex, text)
    for url in detected_urls:
        text = text.replace(url, "urlplaceholder")

    tokens = word_tokenize(text)
    lemmatizer = WordNetLemmatizer()

    clean_tokens = []
    for tok in tokens:
        clean_tok = lemmatizer.lemmatize(tok).lower().strip()
        clean_tokens.append(clean_tok)

    return clean_tokens

### Step 1: Load data and perform a train test split

In [15]:
from sklearn.model_selection import train_test_split
# load data
X, y = load_data()

# perform train test split
X_train, X_test, y_train, y_test = train_test_split(X, y)

### Step 2: Train classifier
* Fit and transform the training data with `CountVectorizer`. Hint: You can include your tokenize function in the `tokenizer` keyword argument!
* Fit and transform these word counts with `TfidfTransformer`.
* Fit a classifier to these tfidf values.

In [16]:
# Import modules
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.ensemble import RandomForestClassifier

# Instantiate transformers and classifier
vect = CountVectorizer(tokenizer=tokenize)
tfidf = TfidfTransformer()
clf = RandomForestClassifier()

# Fit and/or transform each to the data
X_train_counts = vect.fit_transform(X_train)
print('X_train_counts shape:', X_train_counts.shape)
X_train_tfidf = tfidf.fit_transform(X_train_counts)
print('X_train_tfidf shape:', X_train_tfidf.shape)
clf.fit(X_train_tfidf, y_train)

X_train_counts shape: (1802, 5509)
X_train_tfidf shape: (1802, 5509)


RandomForestClassifier()

### Step 3: Predict on test data
* Transform (no fitting) the test data with the same CountVectorizer and TfidfTransformer
* Predict labels on these tfidf values.

In [35]:
# Transform test data
X_test_counts = vect.transform(X_test)
print('X_test_counts shape:', X_test_counts.shape)
X_test_tfidf = tfidf.transform(X_test_counts)
print('X_test_tfidf shape:', X_test_tfidf.shape)

X_test_counts shape: (601, 5509)
X_test_tfidf shape: (601, 5509)


In [19]:
# Predict test labels
y_pred = clf.predict(X_test_tfidf)

### Step 4: Display results
Display a confusion matrix and accuracy score based on the model's predictions.

In [20]:
from sklearn.metrics import confusion_matrix

labels = np.unique(y_pred)
confusion_mat = confusion_matrix(y_test, y_pred)
accuracy = (y_pred == y_test).mean()

print("Labels:", labels)
print("Confusion Matrix:\n", confusion_mat)
print("Accuracy:", accuracy)

Labels: ['Action' 'Dialogue' 'Information']
Confusion Matrix:
 [[ 85   0  30]
 [  0  34   6]
 [  1   0 445]]
Accuracy: 0.9384359400998337


# Final Step: Refactor
Organize these steps into the following functions.

In [ ]:
def display_results():
    # insert step 4 here
    pass


def main():
    # insert steps 1 through 3 here
    pass

In [ ]:
# run program
main()